### ISSUE TITLE
[bug] - Currency fields are not being masked.

### ISSUE THREAD

**Issue by mohdsaquibZS** [tprouvot/mask-sobject#27]
**Describe the bug**
In our org we were trying to mask some amount fields but it is erroring out with error: _Invalid conversion from runtime type Decimal to String Class.MaskSObjectUtils.maskField_

**To Reproduce**
1. add any currency field in the mask sobject fields with any configuration.
2. trriger the masking batch for that object.
3. navigate to the object and check any record.
4. field is not masked
5. check the error log you will se a new line with error:  _Invalid conversion from runtime type Decimal to String Class.MaskSObjectUtils.maskField_

**Expected behavior**
There should be an option for currency masking

**Comment by tprouvot** [comment]
Hi @mohdsaquibZS ,

Thank you for using this functionality! 

Could you detail in which context you are using this framework?
Basically masking is supposed to be on personal information and I would say that currency are not part of this category.
Anyway I'll check the bug, should be easy to fix.

**Comment by mohdsaquibZS** [comment]
Hi @tprouvot,

Thank you for your quick response.

We are using it for masking of PII fields and some other important fields in our full copy sandbox.

Basically we want to hide some amount fields on opportunity object to secure the business data.

And also if possible can you look into date field type also.

Regards,
Mohd Saquib

**Comment by tprouvot** [comment]
Hi @mohdsaquibZS,
Could you test the fix made on [this branch](https://github.com/tprouvot/mask-sobject/tree/fix/currencyField) ?
It solves the issue if you choose `ERASE` mode for currency fields

**Comment by mohdsaquibZS** [comment]
Thanks @tprouvot It worked!
